M48
; DRILL file KiCad 10.0.3 date 2026-07-03T14:54:54
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-03T14:54:54+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X40.733Y-27.279
X40.733Y-32.129
T2
X37.703Y-26.979
X37.703Y-32.429
M30
